GET http://localhost:5000

###################


GET http://localhost:5000/api/libraries

########################


GET http://localhost:5000/api/libraries/Lib1


######################################
POST http://localhost:5000/api/libraries
content-type : application/json


{
    "name":"Lib4"
}

########################
GET http://localhost:5000/api/libraries/Lib1/document/banana


######################################


DELETE http://localhost:5000/api/libraries/Lib4

###############################
DELETE http://localhost:5000/api/libraries/Lib1/document/doc4.txt


